CREATE TABLE INQUIRY_BOARD (
inquiry_num NUMBER PRIMARY KEY,
user_nick VARCHAR2(100) NOT NULL,
inquiry_title VARCHAR2(100) NOT NULL,
inquiry_content CLOB,
inquiry_create_date DATE DEFAULT SYSDATE NOT NULL,
inquiry_ofile VARCHAR2(200),
inquiry_sfile VARCHAR2(300),
downcount NUMBER(5) DEFAULT 0 NOT NULL,
visitcount NUMBER DEFAULT 0 NOT NULL,
CONSTRAINT fk_user_nick_inquiry FOREIGN KEY(user_nick) REFERENCES USERS(user_nick)
ON DELETE CASCADE
);

CREATE TABLE INQUIRY_COMMENT (
inquiry_comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
inquiry_num NUMBER NOT NULL,
user_nick VARCHAR2(100) NOT NULL,
inquiry_comment_content VARCHAR2(1000) NOT NULL,
created_at DATE DEFAULT SYSDATE NOT NULL,
CONSTRAINT fk_inquiry_num FOREIGN KEY (inquiry_num) REFERENCES inquiry_BOARD(inquiry_num)
ON DELETE CASCADE,
CONSTRAINT fk_user_nick_comment_inquiry FOREIGN KEY (user_nick) REFERENCES USERS(user_nick)
ON DELETE CASCADE
);

CREATE SEQUENCE inquiry_comment_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

create sequence inquiry_board_seq
increment by 1  -- 1씩 증가
start with 1    
minvalue 1      
nomaxvalue      
nocycle         
nocache;      



--inquiry 좋아요 테이블 생성
CREATE TABLE INQUIRY_LIKES (
    like_id NUMBER PRIMARY KEY,
    inquiry_num NUMBER NOT NULL,
    user_nick VARCHAR2(100) NOT NULL,
    like_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_like_inquirynew FOREIGN KEY(inquiry_num) REFERENCES INQUIRY_BOARD(inquiry_num)
    ON DELETE CASCADE,
    CONSTRAINT fk_like_usernew FOREIGN KEY(user_nick) REFERENCES USERS(user_nick)
    ON DELETE CASCADE
);

-- inquiry 좋아요 시퀀스 생성
CREATE SEQUENCE inquiry_likes_seq
INCREMENT BY 1
START WITH 1
MINVALUE 1
NOMAXVALUE
NOCYCLE
NOCACHE;

commit;
